name: 🐛 Bug Report
description: Report an issue you are experiencing with the PNut TypeScript Implementation.
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        #### Read this first
        - Provide as many details as possible.

  - type: checkboxes
    attributes:
      label: and have you...
      description: Have you accomplished the following before submitting this issue?
      options:
        - label: I updated to the latest PNut-TS version available
          required: true

  - type: input
    id: affectedRelease
    validations:
      required: true
    attributes:
      label: Version of PNut TypeScript Implementation with the issue
      description: Please specify which version of PNut TypeScript Implementation you are using, and if this is a regression, what is the last known version that worked?
      placeholder: |
        Failing in v1.43.0, last worked in v0.43.1

  - type: dropdown
    id: regression
    validations:
      required: true
    attributes:
      label: Is this a regression?
      multiple: false
      options:
        - Yes. This used to work, but now it doesn't.
        - No or unsure. This never worked, or I haven't tried before.

  - type: textarea
    id: environment
    validations:
      required: true
    attributes:
      label: Hardware, Operating System, Operating System version, PNut-TS version, Node version
      description: |
        Provide details about the machine/software you are running on,
        which operating system this is on, and what PNut-TS & Node version you are using.
        If possible try to replicate the issue in other installations and include your findings here.
      placeholder: |
        Hardware: Mac Pro
        OS Ver: macOS Monterey v12.6.6
        PNut-TS Ver: 1.79.1 (Fm: pnut-ts --help -v)
        Node Ver: 16.13.0
      value: |
        Hardware:
        OS Ver:
        PNut-TS Ver:
        Node Ver:

  - type: textarea
    id: problem
    validations:
      required: true
    attributes:
      label: Description of problem
      description: |
        Explain what the issue is, and how things should look/behave. If possible provide a screenshot with a description.
      placeholder: |
        Please describe the issue you are experiencing.
        (If possible provide a screenshot, or a link to a video, showing the issue)

  - type: textarea
    id: additionalInfo
    validations:
      required: false
    attributes:
      label: Additional information
      description: |
        Is there anything else that you think might help us identify the problem?
        (If possible attach your source file (.spin/.spin2) exhibiting the problem you are describing.)

  - type: markdown
    attributes:
      value: 'Thank you for taking the time to report this issue! By doing so you are helping us make the PNut TypeScript Implementation better.'
