#!/bin/bash
#  the following should abort if the compile fails

# WAS  (set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l   --log resolver parser --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)

#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log outline --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log outline parser --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)

# CRASH OOM!
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log outline resolver parser --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)
#export NODE_OPTIONS="--max-old-space-size=8192"
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log outline resolver parser --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log outline resolver  --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)

#export NODE_OPTIONS="--max-old-space-size=8192"
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js  -v -l -O  --log resolver  --regression element -v TEST/SPIN-tests/spin_test2noTabs.spin2)
