#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/MultSrvo/demo_quadEncTimiPca_exerciser.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/jm_nstrings.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_timi_mates.spin2) # FAIL
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log outline preproc --regression element -- TEST/LARGE-tests/MultSrvo/isp_timi_mates.spin2) # FAIL
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_serial.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_serial_singleton.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_quadEncWBtn_sp.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_mem_strings.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_i2c_singleton.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/isp_i2c_pca9685.spin2)
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O -d --log  outline --regression element -- TEST/LARGE-tests/MultSrvo/demo_quadEncTimiPca_exerciser.spin2)
