#!/bin/bash
#  the following should abort if the compile fails
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -I inc -v --regression preproc --log preproc  -- TEST/PREPROC-tests/include.spin2)
