#!/bin/bash
#  the following should abort if the compile fails
#(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -d -l -O --log compiler resolver preproc parser --regression element -- TEST/LARGE-tests/OctoSerial/demo_octoSystem.spin2)
(set -x;npm run build && ./scripts/doit ./dist/pnut-ts.js -v -l -O -d --log distiller --regression element -- TEST/LARGE-tests/OctoSerial/demo_octoSystem.spin2)
